test: off

clone_folder: c:\prj

build_script: 
    - ps: c:\prj\Build\build.ps1 -Target "Default-CI"

artifacts:
    - path: '**\build-artifact-nuget-packages\*.nupkg'
    - path: '**\build-artifact-cli-packages\*.nupkg'